extends: 'eslint:recommended'
rules:
  indent:
    - 2
    - 4
    - MemberExpression: "off"
  quotes:
    - 2
    - single
  linebreak-style:
    - 2
    - unix
  no-console: "off"
env:
  es6: true
  node: true
parserOptions:
  ecmaVersion: 6
  sourceType: "module"
overrides:
  - 
    files:
      - "tests/automated/*.js"
    env: 
      mocha: true